// =============================================================================
// DOMAINS
// =============================================================================

import { DomainConfig } from "../../types";

export const DOMAINS: DomainConfig[] = [
  // ===== Natura Ecommerce =====
  {
    vendor: "natura",
    country: "BR",
    domain: "https://www.natura.com.br",
    locale: "pt-br",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "brandShowcase",
      "recommendationShowcase",
      "shopTheSet",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  {
    vendor: "natura",
    country: "AR",
    domain: "https://www.naturacosmeticos.com.ar",
    locale: "es-ar",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "brandShowcase",
      "recommendationShowcase",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  {
    vendor: "natura",
    country: "CL",
    domain: "https://www.natura.cl",
    locale: "es-cl",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "brandShowcase",
      "recommendationShowcase",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  {
    vendor: "natura",
    country: "CO",
    domain: "https://www.natura.com.co",
    locale: "es-co",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "brandShowcase",
      "recommendationShowcase",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  {
    vendor: "natura",
    country: "MX",
    domain: "https://www.natura.com.mx",
    locale: "es-mx",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "brandShowcase",
      "recommendationShowcase",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  {
    vendor: "natura",
    country: "PE",
    domain: "https://www.natura.com.pe",
    locale: "es-pe",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "brandShowcase",
      "recommendationShowcase",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  // ===== Natura Social Commerce (Minha Loja) =====
  {
    vendor: "natura",
    country: "BR",
    channel: "socialcommerce",
    domain: "https://www.minhaloja.natura.com",
    locale: "pt-br",
    queryParams: "consultoria=naieli&marca=natura",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  // ===== Avon Social Commerce (Minha Loja) =====
  {
    vendor: "avon",
    country: "BR",
    channel: "socialcommerce",
    domain: "https://www.minhaloja.natura.com",
    locale: "pt-br",
    queryParams: "consultoria=naieli&marca=avon",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "images",
      // "pricing",
      // "shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  // ===== Avon Ecommerce =====
  {
    vendor: "avon",
    country: "BR",
    domain: "https://www.avon.com.br",
    locale: "pt-br",
    availableFeatures: [
      "reviews",
      "reviewFilter",
      "reviewSort",
      "reviewPhotos",
      "reviewRecommendation",
      "images",
      //"pricing",
      //"shipping",
      "rating",
      "ratingConsistency",
      "addToCart",
    ],
  },
  {
    vendor: "avon",
    country: "AR",
    domain: "https://www.avon.com.ar",
    locale: "es-ar",
    availableFeatures: [
      "brandShowcase",
      "images",
      //  "pricing"
      "addToCart",
    ],
  },
  {
    vendor: "avon",
    country: "MX",
    domain: "https://www.avon.mx",
    locale: "es-mx",
    availableFeatures: [
      "brandShowcase",
      "images",
      // "pricing",
      //"shipping",
      "addToCart",
    ],
  },
];
